#!/usr/bin/env Rscript
suppressPackageStartupMessages(library("optparse"))
require('logbuch', quietly = TRUE)
option_list <- list(
    make_option(c("-y", "--year"), type = "character", default = format(Sys.Date(), "%Y"),
                help = "Root-directory where wdlog-files are located [default %default]")
   ,make_option(c("-d", "--directory"), type = "character", default = '.',
                help = "Root-directory where wdlog-files are located [default %default]")
   ,make_option(c("-h", "--hours"), type = "numeric", default = 6.8,
                help = "Hours per day to be worked [default %default]")
    )
parser <- OptionParser(usage = "%prog [options] file.cal", option_list=option_list)

arguments <- parse_args(parser, positional_arguments = 1)
opt <- arguments$options
file <- arguments$args
isWeekend <- function(d) format(d, "%a") %in% c("Sat", "Sun")
if( file.access(file) == -1) {
    stop(sprintf("Specified file ( %s ) does not exist", file))
} else {
    calDays <- parseCalFile(file, year = opt$year)
    writeWdlog(
        dd =
        calDays[!sapply(calDays[,1], isWeekend), ] # filter weekends
       ,path = opt$directory
       ,hours = opt$hours
        )
}
