#!/usr/bin/env Rscript
require('getopt', quietly = TRUE)
opt_spec <- matrix(c(
   'help'   , 'h', 0, "logical"  , "Getting help"
  , 'pattern', 'p', 1, "character", "Pattern to match against Projects"
  , 'from'   , 'f', 1, "character", "Starting Time"
  , 'to'     , 't', 1, "character", "Ending Time"
  , 'format' , 'm', 1, "character", "Time format (default: '%Y-%m-%d')"
  , 'subject', 's', 0, "logical"  , "Should the subjects be appended"
   ), ncol = 5, byrow = TRUE)

# Process command-line arguments
opt <- getopt(spec = opt_spec)
if ( !is.null(opt$help) || length(commandArgs(trailingOnly = TRUE)) == 0 )
{
    cat(getopt(spec = opt_spec, usage = TRUE, command = "extractProjectHours"))
    q(status=0)
}
#opt<- list(
#    pattern = "Lim"
#   ,from = "2013-04-01"
#   ,to = "2013-06-30"
#)
if (is.null(opt$format)) opt$format <- '%Y-%m-%d'
if (is.null(opt$from)) stop("Please specify time when to start looking")
if (is.null(opt$to)) opt$to <- format(Sys.time(), "%Y-%m-%d")

require("logbuch", quietly = TRUE)
wdf <-
  selectWdFiles(
    list.wdfiles(".")
   ,as.POSIXct(opt$from)
   ,as.POSIXct(opt$to)
    )

sm <- summarizeWdFiles(wdf)
i <- grep(opt$pattern, names(sm))
sm.list <-
    apply(
    sm, 1, function (r) {if (all(sapply(r[i], function(x) x == 0))) NULL else r[i]}
    )
sm.df <- do.call(rbind, sm.list[!sapply(sm.list, is.null)])
if (!is.null(opt$subject) && length(i) > 1)
    error("When printing subjects, there could only be one project selected")
if (!is.null(opt$subject))
{
  p <- colnames(sm.df)
  sbjs <-
    sapply(
        rownames(sm.df), function(n)
        {
          f <- wdf[grep(n,wdf)]
          dd <- readDayFile(f)
          dd@subject[which(dd@topic == p)]
        }
        )
  write.csv(data.frame(p = sm.df, Arbeit = sbjs))
} else
    print(sm.df)

q(status = 0)
