#!/usr/bin/Rscript
#================================================================================
# File:        summarizeWorkHours    
# Created:     2011-10-05
# Last Change: Friday, 2012-11-02
# Description: program to summarize work hours
# Usage:       summarize -[w|-week <dir>] -[m|-month <dir>] -[y|-year <dir>]
# ToDo:        write method
# Bugs:        
#             
# Author:      Michel Kuhlmann, <michel@kuhlmanns.info>
# Institution: TK Consult
# Licence:     GNU General Public Licence 
#================================================================================

pkgs = c("logbuch", 'ggplot2', 'reshape2')
es = lapply(pkgs, function(x)suppressMessages(require(x, quietly = TRUE, character.only = TRUE)))

opt <- procCli(commandArgs(TRUE))

#setwd("~/logbuch")    # Development
#opt <- list(week = "2013/07/27",
#            month = "2013/07",
#            year = "2013"
#            )
out_file_names <- 
    list(
         'ts' = kTsPdfName
        ,'project' = kProjPdfName
   )
hours_to_work <- 
    list(
         'week' =  # hours to work per day
            kWeekHoursToWork/kWeekDaysPerWeek
       , 'month' =  #  hours to work per day
            kWeekHoursToWork/kWeekDaysPerWeek
       , 'year' = kWeekHoursToWork
 )
exit_st <-
lapply(names(opt)
     , function(x) 
     {
         log_files <-        # recursive list with workdays-log-files 
             list.wdfiles(opt[[x]])
         workdays.summed <-  # workhours per project and day (data-frame)
             summarizeWdFiles(log_files)
         out.dfs <-          # list of two data-frames: time-series and project
             summarizeTus(
                 ts.df = workdays.summed
                ,tu = x
                ,hours_to_work = hours_to_work[[x]]
                 )
         lapply(names(out.dfs)
              , function(y)
              {
                  p <- plot(out.dfs[[y]])
                  ggsave(p, filename = paste(opt[[x]] , out_file_names[[y]] 
                                           , sep = "/" ) 
                       , width = 12, height = 8.5
                  )
              }
         )
     }
)

q(status = 0)

# End of File ===================================================================
# vim: set ft=r:
