#!/bin/bash
# | Create a template and edit a wdlog-file

[[  $1 == "-h"  || $1 == "--help" ]] && 
{
    echo "Create a template and edit a wdlog-file (WDLOG_DIR has to set in bashrc)"
    echo ""
    echo "Usage: viwdlog"
    exit 0
}

[ -z ${WDLOG_DIR} ] && 
{
    echo "Variable WDLOG_DIR not set in .{zsh,bash}rc" 1>&2
    exit 1
}

[ -z ${EDITOR} ] && 
{
    echo "EDITOR variable not set" 1>&2
    exit 1
}

    
day_log_file=${WDLOG_DIR}/$(date +%Y)/$(date +%m)/$(date +%V)/$(date +%F).wdlog


if [[ ! -e ${day_log_file}  ]]; then
    mkdir -p $(dirname ${day_log_file})
cat << EOF > ${day_log_file}
Date : $(date +%A) $(date +%d) $(date +%B) $(date +%Y)
07.40 - 10.00 | <Project> | <Topic> | <Desc>
10.00 - 12.00 | <Project> | <Topic> | <Desc>
13.00 - 15.00 | <Project> | <Topic> | <Desc>
15.00 - 17.00 | <Project> | <Topic> | <Desc>
EOF
fi

$EDITOR ${day_log_file}
