#!/usr/bin/env Rscript
# | Looks recursively for .wdlog-files and converts them to csv (stdout)
## * Command-line parsing
require('getopt', quietly = TRUE)
opt_spec <- matrix(c(
     'help'      ,'h', 0, "logical"  , "Getting help"
    ,'dir'       ,'d', 1, "character", "Directory to look for wdlog-files"
    ,'output'    ,'o', 1, "character", "Output xlsx-file"
    ,'projconf'  ,'p', 1, "character", "Optional filepath to project-configuration"
   )       , ncol = 5    , byrow = TRUE)

# Process command-line arguments
opt <- getopt(spec = opt_spec)
if ( !is.null(opt$help) || length(commandArgs(trailingOnly = TRUE)) == 0 )
{
    message(
        "Program to look recursively for .wdlog-files and ",
        "convert them to xlsx \n\n")
    cat(getopt(spec = opt_spec, usage = TRUE, command = "wdlogToXlsx"))
    q(status=0)
}

require('logbuch', quietly = TRUE)
require('reshape2', quietly = TRUE)
require('yaml',  quietly = TRUE)
require('xlsx',  quietly = TRUE)

projConf <-           # project-configuration (mapping name to number)
{
    if (!is.null(opt$projconf))
        yaml.load_file(opt$projconf)
    else
        NULL
}

fs <-
    list.files(opt$dir, "\\.wdlog$", recursive = TRUE, full.names = TRUE)
if (length(fs) == 0)
    stop('Could not find any .wdlog-files')
dd <- readWdlogFiles(fs)
odd. <-                                  # output-table
{
    if (!is.null(opt$worker))
        cbind(Worker = opt$worker, dd)
    else
        dd
}
odd <-
{
    if (!is.null(opt$projconf))
        lookupProjects(odd., projConf)
    else
        odd.
}
for (m in levels(odd$Month))
{
    write.xlsx(
        subset(odd, Month == m), file = opt$output,
        sheetName = m, row.names = FALSE, showNA = FALSE)
}
