#!/usr/bin/env Rscript
# | Looks recursively for .wdlog-files and converts them to csv (stdout)
## * Command-line parsing
require('getopt', quietly = TRUE)
opt_spec <- matrix(c(
     'help'      ,'h', 0, "logical"  , "Getting help"
    ,'dir'       ,'d', 1, "character", "Directory to look for wdlog-files"
    ,'worker'    ,'w', 1, "character", "Optional name of worker; added as column"
    ,'projconf'  ,'p', 1, "character", "Optional filepath to project-configuration"
   )       , ncol = 5    , byrow = TRUE)

# Process command-line arguments
opt <- getopt(spec = opt_spec)
if ( !is.null(opt$help) || length(commandArgs(trailingOnly = TRUE)) == 0 )
{
    message(
        "Program to look recursively for .wdlog-files and ",
        "convert them to csv (stdout)\n\n")
    cat(getopt(spec = opt_spec, usage = TRUE, command = "wdlogToCsv"))
    q(status=0)
}
SUFFIX <- "wdlog"
SFP <- sprintf("\\.%s$", SUFFIX)

fpToDate <- function(f) as.POSIXct(sub(SFP, "", basename(f)))
dateToFp <- function(d) paste(as.character(d), SUFFIX, sep = ".")

AMNT <-                             # Month (abbr) - Number Assoc-list
    setNames(c("Jan", "Feb", "Mrz", "Apr", "Mai", "Jun",
               "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"), seq_len(12))
require('logbuch', quietly = TRUE)
require('reshape2', quietly = TRUE)
require('yaml',  quietly = TRUE)

projConf <-           # project-configuration (mapping name to number)
{
    if (!is.null(opt$projconf))
        yaml.load_file(opt$projconf)
    else
        NULL
}

fs <-
    list.files(opt$dir, SFP, recursive = TRUE, full.names = TRUE)
bfs <- basename(fs)
if (length(fs) == 0)
    stop('Could not find any .wdlog-files')
dts <-                                  # all days in date-range
    seq(fpToDate(fs[1]), fpToDate(fs[length(fs)]), by = "day")
dd. <-
    do.call(
        rbind,
        lapply(
            dts, function(d)
        {
            dd. <-
            {
                if (dateToFp(d) %in% bfs)
                    readDayFile( # could also emmit NULL, if parsing fails
                        fs[which(bfs == d)], subProj = TRUE)
                else
                    NULL
            }
            dd <-
            {
                if (is.null(dd.))
                    data.frame(Proj = NA, SubProj = NA, Time = NA, Desc = NA)
                else
                    dd.
            }
            cbind(
                data.frame(
                    Year = format(d, "%Y"),
                    Month = AMNT[[as.numeric(format(d, "%m"))]],
                    Day = format(d, "%d")
                    ), dd)
        }
            ))
dd <-
    dcast(dd., Year + Month + Proj + SubProj ~ Day, value.var = "Time")
odd. <-                                  # output-table
{
    if (!is.null(opt$worker))
        cbind(Worker = opt$worker, dd)
    else
        dd
}
odd <-
{
    if (!is.null(opt$projconf))
        do.call(
            rbind,
            lapply(
                seq_len(nrow(odd.))
                , function(i)
            {
                r <- odd.[i,]
                nm <- r[,4]
                sm <- r[,5]
                ns <-          # project-and subproject number
                {
                    if ( nm %in% names(projConf))
                    {
                        n <-
                        {
                            if (is.numeric(projConf[[nm]]))
                                projConf[[nm]]
                            else
                                projConf[[nm]]$nb
                        }
                        if (is.list(projConf[[nm]]) && sm %in% names(projConf[[nm]]$sb))
                            list(n, projConf[[nm]]$sb[[sm]])
                        else
                            list(n, NA)
                    }
                    else
                        list(NA, NA)
                }
                cbind(r[,1:3],ProjName = r[,5], ProjNb = ns[[1]],
                      SubProjNb = ns[[2]], r[,6:ncol(r)] )
            }
                        )
            )
    else
        odd.
}
# TODO: mapping project-name to number
write.table(
    odd,
    col.names = FALSE, row.names = FALSE, quote = FALSE,
    sep = ";", na = "")
