#!/usr/bin/env Rscript
# | Convert exec-timesheet into csv
args <- commandArgs(TRUE)
if (length(args) != 1 || args[1] %in% c("-h", "--help"))
    stop("Usage: xlsxToCsv TS_AAA_2014.xslx > TS.csv")

f <- args[1]

MONTHS <-
    c("Jan", "Feb", "Mrz", "Apr", "Mai", "Jun",
      "Jul", "Aug", "Sep", "Okt", "Nov", "Dez")
require('methods', quietly = TRUE)
require('xlsx', quietly = TRUE)
fs <-
    strsplit(basename(sub("\\.xlsx", "", f)), "_")[[1]]
worker <- fs[3]
year <- as.numeric(fs[2])
wb <- loadWorkbook(f)
sheets.all <- names(getSheets(wb))
sheets <-                               # sheets with month-data
    sheets.all[sapply(sheets.all, function(s) s %in% MONTHS)]
odf <-
    do.call(
        rbind,
        lapply(
            sheets, function(s)
        {
            dd. <-
                read.xlsx2(
                    f, sheetName = s, header = FALSE, startRow = 4
                    ,colClasses = c("character", "numeric", "numeric", "character", rep("numeric", 31))
                    )
            dd <-                # neglect rows without project-number
                dd.[!sapply(dd.[,2], is.na),]
            if (nrow(dd) == 0)
                NULL
            else
                data.frame(Worker = worker, Year = year, Month = s,
                           TaskName = dd[,1], ProjectNmb = dd[,2],
                           SubProjectNmb = dd[,3], dd[,seq_len(31) + 4]
                           )
        }
            ))
write.table(
    odf, sep = ";", row.names = FALSE, col.names = FALSE,
    quote = FALSE, na = "")
